services:
  web:
    build: .
    container_name: alx_ecommerce_api_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://ecommerce_user:yourpassword@db:5432/ecommerce_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: alx_ecommerce_api_db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
